package model;
// Generated 02/09/2015 16:23:15 by Hibernate Tools 4.3.1



/**
 * ListaipId generated by hbm2java
 */
public class ListaipId  implements java.io.Serializable {


     private long instalacionId;
     private String ip;

    public ListaipId() {
    }

    public ListaipId(long instalacionId, String ip) {
       this.instalacionId = instalacionId;
       this.ip = ip;
    }
   
    public long getInstalacionId() {
        return this.instalacionId;
    }
    
    public void setInstalacionId(long instalacionId) {
        this.instalacionId = instalacionId;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ListaipId) ) return false;
		 ListaipId castOther = ( ListaipId ) other; 
         
		 return (this.getInstalacionId()==castOther.getInstalacionId())
 && ( (this.getIp()==castOther.getIp()) || ( this.getIp()!=null && castOther.getIp()!=null && this.getIp().equals(castOther.getIp()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getInstalacionId();
         result = 37 * result + ( getIp() == null ? 0 : this.getIp().hashCode() );
         return result;
   }   

    @Override
    public String toString()
    {
        return "ListaipId{" + "instalacionId=" + instalacionId + ", ip=" + ip + '}';
    }
   

}


