package model;
// Generated 02/09/2015 16:23:15 by Hibernate Tools 4.3.1



/**
 * Listaip generated by hbm2java
 */
public class Listaip  implements java.io.Serializable {


     private ListaipId id;
     private boolean habil;
     private char estado;
     private String descripcion;

    public Listaip() {
    }

	
    public Listaip(ListaipId id, boolean habil, char estado) {
        this.id = id;
        this.habil = habil;
        this.estado = estado;
    }
    public Listaip(ListaipId id, boolean habil, char estado, String descripcion) {
       this.id = id;
       this.habil = habil;
       this.estado = estado;
       this.descripcion = descripcion;
    }
   
    public ListaipId getId() {
        return this.id;
    }
    
    public void setId(ListaipId id) {
        this.id = id;
    }
    public boolean isHabil() {
        return this.habil;
    }
    
    public void setHabil(boolean habil) {
        this.habil = habil;
    }
    public char getEstado() {
        return this.estado;
    }
    
    public void setEstado(char estado) {
        this.estado = estado;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Override
    public String toString()
    {
        return "Listaip{" + "id=" + id + ", habil=" + habil + ", estado=" + estado + ", descripcion=" + descripcion + '}';
    }
    




}


