package model;
// Generated 02/09/2015 16:23:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log  implements java.io.Serializable {


     private long id;
     private Date fecha;
     private char tipo;
     private String DLog;

    public Log() {
    }

    public Log(long id, Date fecha, char tipo, String DLog) {
       this.id = id;
       this.fecha = fecha;
       this.tipo = tipo;
       this.DLog = DLog;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public char getTipo() {
        return this.tipo;
    }
    
    public void setTipo(char tipo) {
        this.tipo = tipo;
    }
    public String getDLog() {
        return this.DLog;
    }
    
    public void setDLog(String DLog) {
        this.DLog = DLog;
    }




}


