package model;
// Generated 02/09/2015 16:23:15 by Hibernate Tools 4.3.1



/**
 * UltimosorteoId generated by hbm2java
 */
public class UltimosorteoId  implements java.io.Serializable {


     private long instalacionId;
     private int CJuego;
     private String DName;

    public UltimosorteoId() {
    }

    public UltimosorteoId(long instalacionId, int CJuego, String DName) {
       this.instalacionId = instalacionId;
       this.CJuego = CJuego;
       this.DName = DName;
    }
   
    public long getInstalacionId() {
        return this.instalacionId;
    }
    
    public void setInstalacionId(long instalacionId) {
        this.instalacionId = instalacionId;
    }
    public int getCJuego() {
        return this.CJuego;
    }
    
    public void setCJuego(int CJuego) {
        this.CJuego = CJuego;
    }
    public String getDName() {
        return this.DName;
    }
    
    public void setDName(String DName) {
        this.DName = DName;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UltimosorteoId) ) return false;
		 UltimosorteoId castOther = ( UltimosorteoId ) other; 
         
		 return (this.getInstalacionId()==castOther.getInstalacionId())
 && (this.getCJuego()==castOther.getCJuego())
 && ( (this.getDName()==castOther.getDName()) || ( this.getDName()!=null && castOther.getDName()!=null && this.getDName().equals(castOther.getDName()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getInstalacionId();
         result = 37 * result + this.getCJuego();
         result = 37 * result + ( getDName() == null ? 0 : this.getDName().hashCode() );
         return result;
   }   

    @Override
    public String toString()
    {
        return "UltimosorteoId{" + "instalacionId=" + instalacionId + ", CJuego=" + CJuego + ", DName=" + DName + '}';
    }
//   

}


