package model;
// Generated 02/09/2015 16:23:15 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ultimosorteo generated by hbm2java
 */
public class Ultimosorteo  implements java.io.Serializable {


     private UltimosorteoId id;
     private long CSorte;
     private Date FSorte;

    public Ultimosorteo() {
    }

    public Ultimosorteo(UltimosorteoId id, long CSorte, Date FSorte) {
       this.id = id;
       this.CSorte = CSorte;
       this.FSorte = FSorte;
    }
   
    public UltimosorteoId getId() {
        return this.id;
    }
    
    public void setId(UltimosorteoId id) {
        this.id = id;
    }
    public long getCSorte() {
        return this.CSorte;
    }
    
    public void setCSorte(long CSorte) {
        this.CSorte = CSorte;
    }
    public Date getFSorte() {
        return this.FSorte;
    }
    
    public void setFSorte(Date FSorte) {
        this.FSorte = FSorte;
    }

    @Override
    public String toString()
    {
        return "Ultimosorteo{" + "id=" + id.toString()+ ", CSorte=" + CSorte + ", FSorte=" + FSorte + '}';
    }

    


}


